### ISSUE TITLE
Error: '!_debugLocked': is not true

### ISSUE THREAD

**Issue by subhendukundu** [jaumard/rive_splash_screen#2]
```
package:flutter/src/widgets/navigator.dart': Failed assertion: line 4657 pos 12: '!_debugLocked': is not true.
The relevant error-causing widget was
SplashScreen
lib/root_app.dart:30
````

I could have given more important details, but I am super new to flutter.

I am using it like
```
SplashScreen.navigate(
        name: 'assets/riv/logo.riv',
        next: (context) => GraphQLWidgetScreen(),
        until: () => Future.delayed(
          Duration(
            seconds: 2,
          ),
        ),
        startAnimation: 'start',
      ),
```

Tho this works great on flutter web but throwing error on ios emulator. I havent checked in android.

**Comment by jaumard** [comment]
That basically what the example app is doing and it doesn't throw this error, look like it fail pushing your widget to the current navigator for some reason. Difficult to know why, can you give a try to the example app see if you reproduce too ?

**Comment by subhendukundu** [comment]
Can reproduce now,
```
until: () => Future.delayed(
          Duration(
            seconds: 2,
          ),
        ),
```
Throwing error
but not with
```
until: () => Future.delayed(
          Duration(
            seconds: 5,
          ),
        ),
 ```

**Comment by jaumard** [comment]
I've just fixed this :) just do `flutter pub upgrade` and it should work, thanks for the report!
