### ISSUE TITLE
RiveFile() Method not found 

### ISSUE THREAD

**Issue by ThirumaleshFAI** [jaumard/rive_splash_screen#4]
flutter/.pub-cache/hosted/pub.dartlang.org/rive_loading-0.0.3/lib/rive_loading.dart:57:22: Error: Method not found: 'RiveFile'.
        final file = RiveFile();
                     ^^^^^^^^

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  rive: ^0.7.0
  rive_loading: ^0.0.3
  rive_splash_screen: ^0.0.1

Mycode: 
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Responsive(
        mobile: MobileView(),
        desktop: SplashScreen.navigate(
          name: 'fai.riv',
          next: (_) => DesktopView(),
          until: () => Future.delayed(Duration(seconds: 3)),
        ));
  }
}

**Comment by monsterlady** [comment]
same problem, it looked like something wrong with the rive_loading plugin....

**Comment by jaumard** [comment]
Thanks for the report, rive did a breaking changes, I've pushed an update on rive_loading, doing `pub upgrade` should fix this issue now :)
