### ISSUE TITLE
How to play "endAnimation" after the Future has resolved / before the transition to HomePage()

### ISSUE THREAD

**Issue by Wizzel1** [jaumard/rive_splash_screen#5]
Hi there, first of all I want to say thank you for this package. 

So I am a bit confused about how to set up the splashscreen to play the "endAnimation" after the future has resolved. 

Currently, I am doing it like this: 

```
SplashScreen.callback(
        name: 'test.riv',
        startAnimation: 'Start',
        loopAnimation: 'Loop',
        endAnimation: 'End',
        until: () => Future.wait([
          MobileAds.initialize(),
          Firebase.initializeApp(),
          GetStorage.init()
        ]),
        backgroundColor: kBackGroundWhite,
        onError: (error, stacktrace) {},
        onSuccess: (data) {
          Get.to(InnerDrawerScreen());
        },
      ),
```

but it seems like the animation gets interrupted as soon as the future resolves. What am I doing wrong?

So to clarify I'd like this sequence -> StartAnimation - Loopanimation until future resolves - Endanimation - Transition

**Comment by jaumard** [comment]
Hello,

Depending of the time of your callback it can do StartAnimation - EndAnimation if callback is finished during the StartAnimation it should go to the end. 

If that's not the case maybe you can give me your rive file to I can test a bit, maybe there is a bug

**Comment by Wizzel1** [comment]
Yes, you are right. I made a mistake in the animation itself. Everything works as expected now. Thanks!

**Comment by jaumard** [comment]
Cool!!! :) closing then. Don't hesitate to open an issue if there something wrong :)
