### ISSUE TITLE
splash screen not showing on android device 

### ISSUE THREAD

**Issue by Pranavmaid** [jaumard/rive_splash_screen#6]
This is my main file

`import 'package:flutter/material.dart';
import 'package:mileagecalculator/pages/Homepage.dart';
import 'package:mileagecalculator/pages/Savings.dart';
import 'package:rive_splash_screen/rive_splash_screen.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: ThemeData.dark(),
      //home: MyHomePage(),
      home: SplashScreen.navigate(
        backgroundColor: Color(0xFF22262B),
        name: 'animation1.riv',
        next: (context) => MyHomePage(),
        until: () => Future.delayed(Duration(seconds: 5)),
        startAnimation: 'ok',
        alignment: Alignment.center,
        // width: 20,
        // height: 20,
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int selectedPage = 0;

  final _pageOptions = [
    HomePageWidget(),
    CompareWidget(),
  ];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: _pageOptions[selectedPage],
      ),
      bottomNavigationBar: BottomNavigationBar(
        backgroundColor: Color(0xFF22262B),
        items: [
          BottomNavigationBarItem(
            icon: Icon(Icons.trip_origin_rounded),
            label: 'Trip',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.savings_sharp),
            label: 'Savings',
          ),
        ],
        currentIndex: selectedPage,
        onTap: (index) {
          setState(() {
            selectedPage = index;
          });
        },
      ),
    );
  }
}
`
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
my Pubspec File

name: mileagecalculator
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.0+3
  intl: ^0.17.0
  google_fonts: ^2.1.0
  shared_preferences: ^2.0.6
  rive_splash_screen: ^0.1.0
  rive: ^0.7.22

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animation1.riv
    - assets/intro.riv
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Error message

[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Unable to load asset: animation1.riv
E/flutter (28938): #0      PlatformAssetBundle.load
package:flutter/…/services/asset_bundle.dart:224
E/flutter (28938): <asynchronous suspension>
E/flutter (28938):
E/flutter (28938): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: LateInitializationError: Field '_controller@922001788' has not been initialized.
E/flutter (28938): #0      _RiveLoadingState._controller (package:rive_loading/rive_loading.dart)
package:rive_loading/rive_loading.dart:1
E/flutter (28938): #1      _RiveLoadingState._processCallback.<anonymous closure>
package:rive_loading/rive_loading.dart:128
E/flutter (28938): #2      State.setState
package:flutter/…/widgets/framework.dart:1088
E/flutter (28938): #3      _RiveLoadingState._processCallback
package:rive_loading/rive_loading.dart:127
E/flutter (28938): <asynchronous suspension>

Can Someone please help me to solve this issue

**Comment by jaumard** [comment]
Hello,

Just provide the right path to the file:
```
SplashScreen.navigate(
backgroundColor: Color(0xFF22262B),
name: 'assets/animation1.riv',
next: (context) => MyHomePage(),
until: () => Future.delayed(Duration(seconds: 5)),
startAnimation: 'ok',
alignment: Alignment.center,
// width: 20,
// height: 20,
),
```
