### ISSUE TITLE
Unhandled Exception: File contains version 6.3. This runtime supports version 7.0

### ISSUE THREAD

**Issue by Ruslanbek0809** [jaumard/rive_splash_screen#7]
Hi. Can you take a look at this issue. I guess this package depends on rive_loading package. And this dependent package is giving error. Errors i receive:
`Unhandled Exception: File contains version 6.3. This runtime supports version 7.0`
`Unhandled Exception: LateInitializationError: Field '_controller@1442001788' has not been initialized.`

**Comment by jaumard** [comment]
Thanks for the reports! Look like rive need to be updated to support your file. I'll try to do it asap!

**Comment by Ruslanbek0809** [comment]
If it helps package version is: `rive_splash_screen: ^0.1.0`. And may I ask when will it be updated?

**Comment by Ruslanbek0809** [comment]
I guess you are author of this `flare_splash_screen: ^4.0.0` package as well. Do u know how can I add `riv` extension file on this package. I used this package many times with `flr` extension before. But lately Rive 2 released and generated animation file is `riv` now. So I searched and found this `rive_splash_screen` great package. But that above errors occured.

**Comment by jaumard** [comment]
I have check and nothing to do on my side, look like you riv file is from an old version (6.3) of rive, you have to generate the riv file again from riv I guess to have a version 7 or more which will be compatible with this package. I'm not planing on supporting rive bellow 7

> I guess you are author of this flare_splash_screen: ^4.0.0 package as well. Do u know how can I add riv extension file on this package. I used this package many times with flr extension before. But lately Rive 2 released and generated animation file is riv now. So I searched and found this rive_splash_screen great package. But that above errors occured.

That will never append, that's why I created a different package, Flare and Rive runtime and package a totally different.

**Comment by jaumard** [comment]
I'm closing this issue as the package is not the issue here. Let me know if you have other problems once you have updated your file

**Comment by Ruslanbek0809** [comment]
You were right. My designer created rive animation with below version than 7. Thanks for your contribution!
