### ISSUE TITLE
Field '_controller' has not been initialized.

### ISSUE THREAD

**Issue by meg4cyberc4t** [jaumard/rive_splash_screen#9]
I use a single animation for my splash screen. When working, this appears.

The program is working properly, there are no "red screens" with an error, but I am concerned about this entry.
<img width="981" alt="Снимок экрана 2022-03-23 в 22 51 09" src="https://user-images.githubusercontent.com/66907532/159783996-7776b57c-3e90-4012-beb9-b530dc04905b.png">

How do I use this:

```dart
return SplashScreen.callback(
      name: 'assets/rive/loader.riv',
      onError: (_, __) {},
      until: () async {
        Provider.of<UserNotificationsState>(context, listen: false).load();
        Provider.of<UserState>(context, listen: false).load();
        return;
      },
      backgroundColor: Theme.of(context).backgroundColor,
      height: MediaQuery.of(context).size.width * 0.5,
      endAnimation: 'Animation 1',
      onSuccess: (value) => Navigator.of(context).pushReplacement(
        PageRouteBuilder(
            pageBuilder: (BuildContext context, Animation<double> animation,
                    Animation<double> secondaryAnimation) =>
                FadeTransition(
                  opacity: animation,
                  child: routerPage,
                ),
            transitionDuration: const Duration(milliseconds: 700)),
      ),
    );
```

I see that the repository has not been touched since 2021, but please help me)

**Comment by jaumard** [comment]
Hello, thanks for the feedback, that error is indeed weird, I'll take a look and fix before next week :)

**Comment by jaumard** [comment]
@meg4cyberc4t you can do a `dart pub upgrade` I have updated the rive_loading package it should be ok now. Please confirm :)

**Comment by meg4cyberc4t** [comment]
@jaumard  Thank you very much. Everything works! <3
